import type { WorldBank } from "./types";

const bank: WorldBank = {
  slug: "tieng-anh",
  levels: [
    {
      title: "Chào bạn từ mới",
      questions: [
        ["m", "« Con mèo » trong tiếng Anh là gì?", ["dog", "cat", "bird", "fish"], 1, "« Cat » nghĩa là con mèo. Meo meo!"],
        ["t", "« Apple » nghĩa là quả táo.", true, "Đúng rồi! « Apple » là quả táo đỏ ngon lành."],
        ["m", "« Red » là màu gì?", ["Màu đỏ", "Màu xanh lá", "Màu vàng", "Màu đen"], 0, "« Red » là màu đỏ, giống màu quả dâu tây."],
        ["m", "Số « 5 » trong tiếng Anh là gì?", ["four", "six", "five", "nine"], 2, "Số 5 là « five ». Four là 4, six là 6, nine là 9."],
        ["t", "« Pen » nghĩa là cái thước kẻ.", false, "« Pen » là cái bút mực. Thước kẻ là « ruler » nhé."],
        ["m", "« Cặp sách » trong tiếng Anh là gì?", ["book", "pencil", "eraser", "school bag"], 3, "Cặp sách là « school bag ». Book là quyển sách, pencil là bút chì."],
        ["m", "Buổi sáng gặp cô giáo, em chào thế nào?", ["Good night", "Goodbye", "Good morning", "Good evening"], 2, "Buổi sáng ta chào « Good morning ». « Good night » là chúc ngủ ngon."],
        ["t", "« Dog » nghĩa là con chó.", true, "Chính xác! « Dog » là con chó. Gâu gâu!"],
        ["m", "Chọn từ chỉ màu sắc:", ["ten", "blue", "book", "hello"], 1, "« Blue » là màu xanh dương. Các từ còn lại không phải màu sắc."],
        ["m", "« Ten » là số mấy?", ["2", "8", "12", "10"], 3, "« Ten » là số 10, bằng số ngón tay của hai bàn tay em."],
        ["t", "« Goodbye » dùng để chào khi mới gặp nhau.", false, "« Goodbye » là tạm biệt, dùng khi chia tay. Khi gặp nhau ta nói « Hello »."],
        ["m", "« Con chim » trong tiếng Anh là gì?", ["bird", "duck", "fish", "frog"], 0, "Con chim là « bird ». Duck là con vịt, frog là con ếch."],
        ["m", "Bạn hỏi « What's your name? », em trả lời:", ["I'm fine.", "My name is Nam.", "I'm eight.", "Thank you."], 1, "Câu hỏi tên thì trả lời « My name is ... » (Tên mình là ...)."],
        ["t", "« Yellow » nghĩa là màu vàng.", true, "Đúng rồi! « Yellow » là màu vàng như ông mặt trời."],
        ["m", "« Eraser » là đồ dùng gì?", ["Cái bút chì", "Quyển vở", "Cục tẩy", "Cái kéo"], 2, "« Eraser » là cục tẩy, dùng để xóa vết bút chì."],
      ],
    },
    {
      title: "Nhà mình vui ghê",
      questions: [
        ["m", "« Mẹ » trong tiếng Anh là gì?", ["father", "sister", "brother", "mother"], 3, "Mẹ là « mother ». Father là bố, sister là chị/em gái."],
        ["t", "« Grandfather » nghĩa là bà.", false, "« Grandfather » là ông. Bà là « grandmother » nhé."],
        ["m", "Chọn từ đúng: I have ___ apple.", ["a", "two", "an", "some"], 2, "« Apple » bắt đầu bằng nguyên âm a nên dùng « an »: an apple."],
        ["m", "Chọn từ đúng: This is ___ cat.", ["a", "an", "two", "these"], 0, "« Cat » bắt đầu bằng phụ âm c nên dùng « a »: a cat."],
        ["t", "« Milk » nghĩa là sữa.", true, "Đúng rồi! « Milk » là sữa, uống sữa giúp em cao lớn."],
        ["m", "Số nhiều của « book » là gì?", ["bookes", "books", "bookies", "book"], 1, "Hầu hết danh từ chỉ cần thêm « s » khi số nhiều: books."],
        ["m", "Hỏi « How old are you? », em trả lời:", ["I'm nine years old.", "I'm fine, thanks.", "I'm from Viet Nam.", "I'm a student."], 0, "« How old are you? » hỏi tuổi, nên trả lời « I'm nine years old. »"],
        ["t", "« Bread » nghĩa là cơm.", false, "« Bread » là bánh mì. Cơm là « rice »."],
        ["m", "Chọn từ khác loại:", ["rice", "bread", "milk", "sister"], 3, "« Sister » chỉ người trong gia đình, các từ còn lại là đồ ăn, đồ uống."],
        ["m", "Số nhiều của « box » là gì?", ["boxs", "box", "boxes", "boxies"], 2, "Từ tận cùng bằng x, s, ch, sh thì thêm « es »: boxes."],
        ["t", "« Brother » nghĩa là anh trai hoặc em trai.", true, "Chính xác! « Brother » dùng cho cả anh trai và em trai."],
        ["m", "« Đôi mắt » trong tiếng Anh là gì?", ["ears", "eyes", "hands", "legs"], 1, "Đôi mắt là « eyes ». Ears là tai, hands là bàn tay, legs là chân."],
        ["m", "Chọn từ đúng: My father's mother is my ___.", ["aunt", "sister", "mother", "grandmother"], 3, "Mẹ của bố là bà nội, tiếng Anh là « grandmother »."],
        ["t", "Số nhiều của « child » là « childs ».", false, "Số nhiều của « child » là « children », đây là từ đặc biệt."],
        ["m", "Mời bạn ăn, em nói: « Would you like some ___? »", ["cake", "book", "pen", "desk"], 0, "Mời ăn thì dùng đồ ăn: « Would you like some cake? » (Bạn ăn bánh không?)"],
      ],
    },
    {
      title: "Ngữ pháp siêu nhí",
      questions: [
        ["m", "Chọn từ đúng: She ___ a teacher.", ["am", "are", "is", "be"], 2, "« She » (cô ấy) đi với « is »: She is a teacher."],
        ["t", "« They are students. » là câu đúng.", true, "Đúng rồi! « They » (họ) luôn đi với « are »."],
        ["m", "Chọn từ đúng: I ___ a new bike.", ["has", "is", "am", "have"], 3, "« I » đi với « have »: I have a new bike (Tớ có xe đạp mới)."],
        ["m", "Chọn từ đúng: My brother ___ two cats.", ["have", "has", "is", "are"], 1, "« My brother » là một người (như « he ») nên dùng « has »."],
        ["t", "Câu « He can swims. » là câu đúng.", false, "Sau « can » dùng động từ nguyên mẫu: « He can swim. »"],
        ["m", "Chọn từ đúng: The ball is ___ the box. (bên trong)", ["in", "on", "under", "behind"], 0, "« In » nghĩa là bên trong: quả bóng ở trong hộp."],
        ["m", "Chọn từ đúng: We ___ in class 4A.", ["is", "am", "be", "are"], 3, "« We » (chúng tớ) đi với « are »: We are in class 4A."],
        ["t", "« Under » nghĩa là ở dưới.", true, "Chính xác! « Under the table » là ở dưới gầm bàn."],
        ["m", "« Can you dance? » – Nam biết nhảy. Nam trả lời:", ["Yes, I can.", "Yes, I do.", "No, I can't.", "Yes, I am."], 0, "Hỏi bằng « Can » thì trả lời bằng « can »: Yes, I can."],
        ["m", "Chọn từ đúng: The cat is ___ the table. (ở trên)", ["under", "on", "in", "next"], 1, "« On » nghĩa là ở trên (chạm vào mặt bàn): on the table."],
        ["t", "Câu « There are a pen on the desk. » là câu đúng.", false, "Một cái bút là số ít nên dùng « There is a pen on the desk. »"],
        ["m", "Chọn câu đúng:", ["I is happy.", "You am tall.", "He is my friend.", "They is here."], 2, "« He » đi với « is ». Nhớ nhé: I am, you/we/they are, he/she/it is."],
        ["m", "Hỏi « Where is the lamp? », câu trả lời đúng là:", ["It's next to the bed.", "It's blue.", "Yes, it is.", "It's a lamp."], 0, "« Where » hỏi ở đâu, nên trả lời vị trí: next to the bed (bên cạnh giường)."],
        ["t", "Câu « She has long hair. » là câu đúng.", true, "Đúng rồi! « She » đi với « has »: Cô ấy có mái tóc dài."],
        ["m", "Chọn từ đúng: ___ you play the piano? – Yes, I can.", ["Do", "Can", "Are", "Is"], 1, "Câu trả lời là « Yes, I can » nên câu hỏi phải bắt đầu bằng « Can »."],
      ],
    },
    {
      title: "Một ngày bận rộn",
      questions: [
        ["m", "Chọn từ đúng: He ___ football every Sunday.", ["plays", "play", "playing", "is play"], 0, "Thói quen dùng hiện tại đơn; « He » thì động từ thêm s: plays."],
        ["t", "Câu « She go to school by bus. » là câu đúng.", false, "Chủ ngữ « She » thì động từ thêm s/es: « She goes to school by bus. »"],
        ["m", "Chọn từ đúng: Look! The children ___ in the park.", ["plays", "are playing", "play", "is playing"], 1, "« Look! » báo việc đang xảy ra, dùng hiện tại tiếp diễn: are playing."],
        ["m", "« Doctor » là nghề gì?", ["Giáo viên", "Nông dân", "Công nhân", "Bác sĩ"], 3, "« Doctor » là bác sĩ, người chữa bệnh cho mọi người."],
        ["t", "« It's rainy today. » nghĩa là « Hôm nay trời mưa. »", true, "Đúng rồi! « Rainy » là có mưa. Nhớ mang ô nhé!"],
        ["m", "« A farmer » làm việc ở đâu?", ["In a hospital", "In a school", "On a farm", "In a factory"], 2, "« Farmer » là nông dân, làm việc trên cánh đồng, trang trại: on a farm."],
        ["m", "Chọn từ đúng: What time ___ you get up?", ["does", "do", "are", "is"], 1, "Chủ ngữ « you » dùng trợ động từ « do »: What time do you get up?"],
        ["t", "« Seven thirty » nghĩa là 7 giờ 15 phút.", false, "« Seven thirty » là 7 giờ 30 phút. 7 giờ 15 là « seven fifteen »."],
        ["m", "Chọn từ đúng: My mother ___ TV now.", ["watch", "watches", "is watching", "watched"], 2, "Có « now » (bây giờ) nên dùng hiện tại tiếp diễn: is watching."],
        ["m", "Chọn từ đúng: Linh ___ like fish.", ["doesn't", "don't", "isn't", "aren't"], 0, "« Linh » là một người (như « she ») nên phủ định dùng « doesn't »."],
        ["t", "« Tuesday » là thứ Ba.", true, "Chính xác! Monday là thứ Hai, Tuesday là thứ Ba."],
        ["m", "Hỏi « What's the weather like? », câu trả lời hợp lý:", ["It's Monday.", "It's seven o'clock.", "It's a bird.", "It's sunny."], 3, "Câu hỏi về thời tiết, nên trả lời « It's sunny. » (Trời nắng)."],
        ["m", "Chọn từ đúng: ___ does your father do? – He's a driver.", ["Where", "When", "What", "Who"], 2, "« What does your father do? » là câu hỏi về nghề nghiệp."],
        ["t", "Câu « I am write a letter now. » là câu đúng.", false, "Hiện tại tiếp diễn là am/is/are + V-ing: « I am writing a letter now. »"],
        ["m", "Chọn từ đúng: Does she ___ English on Monday?", ["has", "having", "to have", "have"], 3, "Sau « Does » dùng động từ nguyên mẫu: Does she have English on Monday?"],
      ],
    },
    {
      title: "Nhà thám hiểm tài ba",
      questions: [
        ["m", "Chọn từ đúng: Yesterday I ___ to the zoo.", ["go", "went", "goes", "going"], 1, "« Yesterday » là quá khứ; quá khứ của « go » là « went »."],
        ["t", "Quá khứ của « play » là « played ».", true, "Đúng rồi! « Play » là động từ có quy tắc, thêm « ed »: played."],
        ["m", "Chọn từ đúng: An elephant is ___ than a dog.", ["big", "biggest", "bigger", "more big"], 2, "So sánh hơn của « big » là « bigger » (gấp đôi chữ g rồi thêm er)."],
        ["m", "Chọn từ đúng: ___ you at home last night?", ["Were", "Was", "Did", "Are"], 0, "« Last night » là quá khứ; « you » đi với « were »."],
        ["t", "Câu « She didn't went to school. » là câu đúng.", false, "Sau « didn't » dùng động từ nguyên mẫu: « She didn't go to school. »"],
        ["m", "Chọn từ đúng: My ruler is ___ than yours.", ["long", "longest", "more long", "longer"], 3, "Tính từ ngắn thêm « er » khi so sánh hơn: longer than."],
        ["m", "Chọn từ đúng: This book is ___ interesting than that one.", ["more", "most", "very", "much"], 0, "Tính từ dài như « interesting » dùng « more ... than »."],
        ["t", "« Better » là dạng so sánh hơn của « good ».", true, "Chính xác! « Good » là từ đặc biệt: good → better."],
        ["m", "Hỏi « What did you do last weekend? », câu trả lời hợp lý:", ["I visit my grandma.", "I'm visiting my grandma.", "I will visit my grandma.", "I visited my grandma."], 3, "Hỏi về cuối tuần trước thì trả lời bằng quá khứ đơn: I visited my grandma."],
        ["m", "Chọn từ đúng: Mai ___ her homework two hours ago.", ["does", "is doing", "did", "do"], 2, "« Two hours ago » (2 giờ trước) là quá khứ; quá khứ của « do » là « did »."],
        ["t", "Quá khứ của « buy » là « buyed ».", false, "« Buy » là động từ bất quy tắc, quá khứ là « bought »."],
        ["m", "Chọn từ đúng: Summer is ___ than winter.", ["hot", "hotter", "hoter", "more hot"], 1, "So sánh hơn của « hot » là « hotter » (gấp đôi chữ t rồi thêm er)."],
        ["m", "Chọn từ đúng: ___ did you go to Da Lat? – Last summer.", ["What", "Where", "Who", "When"], 3, "Câu trả lời là thời gian (Last summer) nên hỏi bằng « When »."],
        ["t", "Câu « Tom is taller than Peter. » là câu so sánh hơn đúng.", true, "Đúng rồi! « Taller than » nghĩa là cao hơn."],
        ["m", "Ở thư viện, bạn Nam nói to. Em nhắc bạn thế nào?", ["Please be quiet.", "Please speak louder.", "Let's sing a song.", "Please run fast."], 0, "Ở thư viện cần giữ yên lặng: « Please be quiet. » (Làm ơn giữ trật tự)."],
      ],
    },
  ],
};

export default bank;
